version: '3.9'

services:
  file_twins:
    image: file_twins
    build: .
    container_name: file_twins
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config.json:/config.json
      - /Volumes/Ssd/mt-photos:/mt-photos_origin
      - /Volumes/Raid/mt-photos:/mt-photos_dest
      - /Users/zhtut/mt-photos/config:/config_origin
      - /Volumes/Raid/mt-photos_config:/config_dest
