version: '3.9'

services:
  app:
    image: file_twins
    build: .
    container_name: file_twins
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config.json:/config.json
      - /Volumes/Media/mt-photos:/origin
      - /Volumes/Raid/mt_photos:/dest
