version: '3.9'

services:
  file_twins:
    image: file_twins
    build: .
    container_name: file_twins
    restart: always
    user: $USER
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config.json:/config.json
      - /Volumes/Ssd/mt-photos:/origin
      - /Volumes/Raid/mt-photos:/dest
